#!/usr/bin/env python3
"""
Simple test script for Ant Agent to demonstrate functionality without API calls.
"""

import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent))

from ant_agent.agent.ant_agent import AntAgent
from ant_agent.tools.bash_tool import BashTool
from ant_agent.tools.edit_tool import EditTool, CreateFileTool
from ant_agent.tools.thinking_tool import SequentialThinkingTool
from ant_agent.tools.task_done_tool import TaskDoneTool
from ant_agent.utils.config import AgentConfig, ModelConfig, LLMProvider

def test_tools():
    """Test individual tools without LLM."""
    print("🧪 Testing Ant Agent Tools...")

    # Test thinking tool
    print("\n1. Testing Sequential Thinking Tool:")
    thinking_tool = SequentialThinkingTool()
    result1 = thinking_tool.run(thought="I need to create a hello world script")
    print(f"   {result1.output}")
    result2 = thinking_tool.run(thought="I'll use the create_file tool to make hello.py")
    print(f"   {result2.output}")

    # Test create file tool
    print("\n2. Testing Create File Tool:")
    create_tool = CreateFileTool()
    hello_content = '''#!/usr/bin/env python3
"""
Hello World script created by Ant Agent.
"""

def main():
    print("Hello, World!")
    print("This script was generated by Ant Agent using LangChain.")

if __name__ == "__main__":
    main()
'''
    result3 = create_tool.run(file_path="hello.py", content=hello_content)
    print(f"   {result3.output}")

    # Test bash tool
    print("\n3. Testing Bash Tool:")
    bash_tool = BashTool()
    result4 = bash_tool.run(command="python3 hello.py")
    print(f"   {result4.output}")

    # Test task done tool
    print("\n4. Testing Task Done Tool:")
    task_done_tool = TaskDoneTool()
    result5 = task_done_tool.run(summary="Successfully created and tested hello.py script")
    print(f"   {result5.output}")

    # Show thinking summary
    print("\n🧠 Thinking Summary:")
    print(thinking_tool.get_thinking_summary())

    print("\n✅ All tools are working correctly!")

def test_configuration():
    """Test configuration system."""
    print("\n📋 Testing Configuration System...")

    # Create test configuration
    model_config = ModelConfig(
        model_provider=LLMProvider.OPENAI,
        model="gpt-4",
        api_key="test-key"
    )

    agent_config = AgentConfig(
        name="test_agent",
        model="test_model",
        max_steps=10,
        tools=["bash", "create_file", "sequential_thinking", "task_done"]
    )

    print(f"   Agent: {agent_config.name}")
    print(f"   Model: {model_config.model}")
    print(f"   Provider: {model_config.model_provider}")
    print(f"   Max Steps: {agent_config.max_steps}")
    print(f"   Tools: {', '.join(agent_config.tools)}")

    print("✅ Configuration system working correctly!")

def main():
    """Run all tests."""
    print("🚀 Ant Agent Testing Suite")
    print("=" * 40)

    try:
        test_configuration()
        test_tools()

        print("\n🎉 All tests passed! Ant Agent is ready to use.")
        print("\nTo use with real LLM providers:")
        print("1. Edit ant_config.yaml with your API keys")
        print("2. Run: ant-cli run 'your task here'")
        print("3. Or run: ant-cli interactive for conversational mode")

    except Exception as e:
        print(f"\n❌ Test failed: {str(e)}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()